#!/bin/bash
# this is the GPIO pin receiving the shut-down signal
GPIOpin1=3
echo "$GPIOpin1" > /sys/class/gpio/export
echo "in" > /sys/class/gpio/gpio$GPIOpin1/direction
while true; do
  sleep 1
  power=$(cat /sys/class/gpio/gpio$GPIOpin1/value)
  if [ $power != 1 ]; then
    echo "out" > /sys/class/gpio/gpio$GPIOpin1/direction
    echo "0" > /sys/class/gpio/gpio$GPIOpin1/value
    sleep 3
    ssh 'root@192.168.0.12' 'shutdown -h now'
    sleep 5
    sudo shutdown -h now
  fi
done
